import type { Incident } from "./types";

// Seed incident history. These are also what "Seed Hindsight" retains into the memory bank.
export const DEMO_INCIDENTS: Incident[] = [
  { id: "INC-001", service: "Auth Service", environment: "Production", severity: "High", errorCode: "HTTP 401", title: "Authentication failures after key rotation", description: "Users receiving 401 on login; JWT validation failing across all regions.", rootCause: "JWKS cache held the retired signing key after scheduled rotation", resolution: "Flushed JWKS cache and reduced cache TTL from 24h to 15m", outcome: "Logins recovered in 6 minutes; no recurrence after TTL change", status: "Resolved", timestamp: "2026-05-04T08:12:00Z" },
  { id: "INC-002", service: "Search API", environment: "Production", severity: "Medium", errorCode: "HTTP 504", title: "API gateway timeouts on search", description: "Gateway returning 504 for /search on queries with many filters.", rootCause: "Missing composite index on products(category, price)", resolution: "Added composite index; set gateway upstream timeout to 15s", outcome: "p99 dropped from 31s to 420ms", status: "Resolved", timestamp: "2026-05-09T14:40:00Z" },
  { id: "INC-003", service: "Worker Fleet", environment: "Production", severity: "High", errorCode: "OOMKilled", title: "Container crash loop in job workers", description: "Worker pods restarting repeatedly with OOMKilled status.", rootCause: "Memory leak in image-processing library retaining buffers", resolution: "Pinned library to previous version and raised memory limit 512Mi→1Gi", outcome: "Crash loop stopped; upstream bug reported", status: "Resolved", timestamp: "2026-05-15T03:22:00Z" },
  { id: "INC-004", service: "Payment API", environment: "Production", severity: "Critical", errorCode: "HTTP 503", title: "Payment API returning 503", description: "Payment API returning 503 errors; database connections timing out under checkout load.", rootCause: "Database connection pool exhausted (max 50) during traffic peak", resolution: "Increased pool size from 50 to 100 and set connection timeout to 5s", outcome: "Error rate returned to baseline within 10 minutes", status: "Resolved", timestamp: "2026-05-22T19:05:00Z" },
  { id: "INC-005", service: "Logging Pipeline", environment: "Production", severity: "Medium", errorCode: "ENOSPC", title: "Disk space exhaustion on log nodes", description: "Log shippers failing with 'no space left on device'.", rootCause: "Log rotation disabled after config migration", resolution: "Re-enabled logrotate, purged logs older than 7 days", outcome: "Disk usage dropped from 100% to 41%", status: "Resolved", timestamp: "2026-05-28T11:18:00Z" },
  { id: "INC-006", service: "Session Cache", environment: "Production", severity: "High", errorCode: "Redis TIMEOUT", title: "Redis timeouts on session reads", description: "Session lookups timing out; users logged out randomly.", rootCause: "Redis memory pressure triggering aggressive eviction and slow commands (KEYS *)", resolution: "Removed KEYS usage, set maxmemory-policy allkeys-lru, scaled to 8GB", outcome: "Timeouts eliminated", status: "Resolved", timestamp: "2026-06-02T16:47:00Z" },
  { id: "INC-007", service: "Checkout Web", environment: "Production", severity: "High", errorCode: "Deploy failed", title: "Deployment failure on checkout release", description: "Rollout stuck; new pods failing readiness probe.", rootCause: "Missing environment variable STRIPE_WEBHOOK_SECRET in new release", resolution: "Rolled back, added variable to deployment manifest, redeployed", outcome: "Release completed on second attempt", status: "Resolved", timestamp: "2026-06-08T10:02:00Z" },
  { id: "INC-008", service: "Inventory Service", environment: "Production", severity: "Medium", errorCode: "Deadlock", title: "Database deadlocks on inventory updates", description: "Intermittent 'deadlock detected' errors during flash sale.", rootCause: "Two code paths locking rows in opposite order", resolution: "Standardised lock ordering by SKU id; added retry with backoff", outcome: "Deadlocks reduced to zero", status: "Resolved", timestamp: "2026-06-14T13:30:00Z" },
  { id: "INC-009", service: "Recommendation API", environment: "Production", severity: "Medium", errorCode: "CPU 98%", title: "CPU spike on recommendation nodes", description: "CPU pinned near 100%, latency degraded.", rootCause: "Regex catastrophic backtracking on malformed user agent strings", resolution: "Replaced regex with parser, added input length cap", outcome: "CPU back to 35%", status: "Resolved", timestamp: "2026-06-20T07:55:00Z" },
  { id: "INC-010", service: "Notification Service", environment: "Staging", severity: "Low", errorCode: "ETIMEDOUT", title: "Network timeouts to email provider", description: "Outbound SMTP calls timing out from staging.", rootCause: "Egress firewall rule removed during VPC change", resolution: "Restored egress rule for port 587", outcome: "Email delivery restored", status: "Resolved", timestamp: "2026-06-25T09:10:00Z" },
  { id: "INC-011", service: "Order API", environment: "Production", severity: "Critical", errorCode: "Timeout", title: "Order API database saturation", description: "Order API requests timing out; database connection saturation observed.", rootCause: "Database connection saturation; pool too small for new replica count", resolution: "Increased connection pool and restarted API pods", outcome: "Throughput recovered; pool sizing added to capacity checklist", status: "Resolved", timestamp: "2026-07-01T18:22:00Z" },
  { id: "INC-012", service: "Payment API", environment: "Production", severity: "High", errorCode: "HTTP 502", title: "Payment provider TLS errors", description: "Upstream provider calls failing with TLS handshake errors.", rootCause: "Provider rotated intermediate certificate; outdated CA bundle in image", resolution: "Updated base image CA certificates and redeployed", outcome: "Resolved in 25 minutes", status: "Resolved", timestamp: "2026-07-06T12:14:00Z" },
  { id: "INC-013", service: "Analytics Worker", environment: "Production", severity: "Medium", errorCode: "Memory leak", title: "Gradual memory growth in analytics worker", description: "RSS grows ~200MB/hour until restart.", rootCause: "Unbounded in-process cache of event schemas", resolution: "Added LRU bound of 1000 entries", outcome: "Memory flat for 7 days", status: "Resolved", timestamp: "2026-07-12T05:40:00Z" },
  { id: "INC-014", service: "API Gateway", environment: "Production", severity: "High", errorCode: "HTTP 504", title: "Gateway timeout for mobile clients", description: "Mobile clients receiving 504 on /v2 endpoints.", rootCause: "Upstream keepalive misconfiguration causing connection churn", resolution: "Enabled upstream keepalive (64 conns)", outcome: "504 rate from 4% to 0.01%", status: "Resolved", timestamp: "2026-07-18T15:33:00Z" },
  { id: "INC-015", service: "Catalog Service", environment: "Production", severity: "Medium", errorCode: "CrashLoopBackOff", title: "Catalog pods crash on start", description: "Pods crash-looping after node pool upgrade.", rootCause: "Liveness probe too aggressive for slower cold start", resolution: "Added startupProbe with 60s budget", outcome: "Pods stable", status: "Resolved", timestamp: "2026-07-24T20:01:00Z" },
  { id: "INC-016", service: "Session Cache", environment: "Production", severity: "High", errorCode: "Redis TIMEOUT", title: "Redis timeouts during batch job", description: "Session reads timing out while nightly batch runs.", rootCause: "Batch job issuing large MGET on the same Redis primary; memory pressure", resolution: "Moved batch to read replica; split MGET into chunks of 100", outcome: "No timeouts on subsequent runs", status: "Resolved", timestamp: "2026-08-01T01:15:00Z" },
  { id: "INC-017", service: "Auth Service", environment: "Production", severity: "Critical", errorCode: "HTTP 500", title: "Auth DB failover errors", description: "500 errors during managed DB failover.", rootCause: "Clients cached DNS of old primary", resolution: "Lowered DNS TTL, enabled driver reconnect on failover", outcome: "Next failover had 8s blip only", status: "Resolved", timestamp: "2026-08-09T22:48:00Z" },
  { id: "INC-018", service: "Payment API", environment: "Production", severity: "Critical", errorCode: "HTTP 503", title: "API 503 caused by DB connection exhaustion", description: "Payment API 503s after a new release increased per-request queries.", rootCause: "DB connection exhaustion; new release held connections during external calls", resolution: "Adjusted pool configuration and released connections before provider calls", outcome: "503s stopped; code review checklist updated", status: "Resolved", timestamp: "2026-08-17T17:26:00Z" },
  { id: "INC-019", service: "Payment API", environment: "Production", severity: "High", errorCode: "HTTP 500", title: "Payment API failure on refunds", description: "Refund endpoint returning 500 for a subset of merchants.", status: "Investigating", timestamp: "2026-09-24T09:40:00Z" },
  { id: "INC-020", service: "Session Cache", environment: "Production", severity: "High", errorCode: "Redis TIMEOUT", title: "Redis timeout", description: "Redis command timeouts on session cluster during peak.", rootCause: "Redis memory pressure from large session payloads", resolution: "Trimmed session payload, raised maxmemory, enabled LRU eviction", outcome: "Latency normalised", status: "Resolved", timestamp: "2026-09-25T13:05:00Z" },
  { id: "INC-021", service: "Order API", environment: "Production", severity: "Critical", errorCode: "HTTP 503", title: "API returning HTTP 503", description: "Order API returning 503 while DB connections time out.", rootCause: "Database connection pool exhausted", resolution: "Raised pool size and added pool saturation alert at 80%", outcome: "Recovered in 12 minutes", status: "Resolved", timestamp: "2026-09-26T21:30:00Z" },
];

export const DEMO_SCENARIO = {
  service: "Payment API",
  environment: "Production" as const,
  severity: "Critical" as const,
  errorCode: "HTTP 503",
  description: "Production Payment API is returning HTTP 503 errors and database connections are timing out.",
  symptoms: "5xx rate at 38%, p99 latency 12s, DB connection wait time climbing, checkout conversions dropping.",
};

export function incidentToMemoryText(i: {
  id: string; service: string; environment: string; severity: string; errorCode?: string;
  description: string; rootCause?: string; resolution?: string; outcome?: string; timestamp: string;
}) {
  return [
    `Incident ${i.id} (${i.severity}, ${i.environment}) on ${i.service} at ${i.timestamp}.`,
    i.errorCode ? `Error: ${i.errorCode}.` : "",
    `Description: ${i.description}`,
    i.rootCause ? `Root cause: ${i.rootCause}.` : "",
    i.resolution ? `Resolution: ${i.resolution}.` : "",
    i.outcome ? `Outcome: ${i.outcome}.` : "",
  ].filter(Boolean).join(" ");
}
